# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9519440d05efb7205d4f895ccbe06f6500ecaa9281eed294858baaef38e45a1905936dcedc79dad04dd8be8ec56b78dcce7a09f8837d5d68f79a987958bba26b

test:
  secret_key_base: e59334befc158eafff105eaed576e4cd5856edf0eae3cf86b79b6f5174dc57b71a1e63930b50eefaae24055f22db26cb58d89b33bbac79b97787e55b386e899b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
